FROM jupyter/scipy-notebook

USER root

RUN apt-get update &&\
    apt-get install -y libjpeg-dev \
                       zlib1g-dev \
                       libpng12-dev \
                       python-pip \
                       wget \
                       vim \
                       libkrb5-dev \
                       libxml2-dev \
                       libxslt-dev \
                       libjpeg-dev \
                       zlib1g-dev \
                       libpng12-dev \
                       libpulse-dev \
                       swig \
                       libx11-dev \
                       libtool \
                       libffi-dev \
                       ruby \
                       ruby-dev \
                       make \
                       libzmq-dev \
                       autoconf \
                       pkg-config \
                       curl \
                       libkrb5-dev \
                       krb5-user \
                       vim \
                       software-properties-common \
                       less \
                       git \
                       python3 \
                       python3-dev  \
                       python3-software-properties



# Add HDP repo
RUN curl -Lk http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.5.6.0/hdp.list -o /etc/apt/sources.list.d/hdp.list &&\
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B9733A7A07513CAD &&\
    apt-get update

# R pre-requisites
RUN apt-get install -y --no-install-recommends \
    fonts-dejavu \
    gfortran \
    gcc && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

